language: cpp
dist: trusty
addons:
  apt:
    sources:
    - llvm-toolchain-trusty-5.0

    packages:
    - cmake
    - libboost-filesystem-dev
    - libboost-test-dev
    - clang-5.0
compiler:
- clang
os:
- linux
script:
- export CXX=g++
- export CC=gcc
- export CODECOV_TOKEN="c3d08772-6107-422c-886f-ada5c4780d5c"
- mkdir build && cd build
- cmake .. -DINOTIFY_GCC_COVERAGE=1
- cmake --build .
- ./test/unit/inotify_unit_test
- bash <(curl -s https://codecov.io/bash)

